server.port=8888

logging.config=classpath:log4j2.xml
logging.level.ROOT=INFO
logging.level.com.zero=DEBUG

# ??Actuator?loggers??
management.endpoints.web.exposure.include=loggers
management.endpoint.loggers.enabled=true
